<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Ten99.Aria.Integration.Graph.Email</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ten99.Aria.Integration.Graph\Ten99.Aria.Integration.Graph.csproj" />
  </ItemGroup>

</Project>
